import { CheckOutlined, DownloadOutlined, RocketOutlined } from '@ant-design/icons'
import { Button, Segmented, Table, Tag, message } from 'antd'
import { useState } from 'react'
import { formatPrice } from '../fields/field.data'
import { transactions } from './owner.data'

export function OwnerSubscriptionPage() {
  const [tab, setTab] = useState<'plan' | 'transactions'>('plan'); const [messageApi, contextHolder] = message.useMessage()
  return <section className="owner-page">{contextHolder}<header className="user-page__head"><div><span className="eyebrow">BILLING NODE</span><h1>Gói dịch vụ & giao dịch</h1><p>Quản lý quyền lợi portal và dòng tiền của cơ sở.</p></div></header><Segmented value={tab} onChange={setTab} options={[{ value: 'plan', label: 'Gói dịch vụ' }, { value: 'transactions', label: 'Lịch sử giao dịch' }]} />{tab === 'plan' ? <><article className="current-plan"><div><RocketOutlined /><span><small>GÓI HIỆN TẠI</small><h2>PRO FACILITY</h2><p>Gia hạn vào 22/11/2026</p></span></div><strong>499.000đ<small>/tháng</small></strong><Button onClick={() => messageApi.success('Yêu cầu quản lý gói đã được ghi nhận.')}>Quản lý gói</Button></article><div className="plan-grid">{[{ name: 'Starter', price: 'Miễn phí', features: ['1 sân', 'Booking cơ bản', 'Báo cáo tháng'] }, { name: 'Pro Facility', price: '499.000đ', features: ['Không giới hạn sân', 'Giá linh hoạt', 'Báo cáo nâng cao', 'Hỗ trợ ưu tiên'] }, { name: 'Enterprise', price: 'Liên hệ', features: ['Nhiều chi nhánh', 'API riêng', 'Quản lý tài khoản', 'SLA tùy chỉnh'] }].map((plan) => <article className={plan.name === 'Pro Facility' ? 'featured' : ''} key={plan.name}><h2>{plan.name}</h2><strong>{plan.price}</strong><ul>{plan.features.map((feature) => <li key={feature}><CheckOutlined /> {feature}</li>)}</ul><Button type={plan.name === 'Pro Facility' ? 'primary' : 'default'} block>{plan.name === 'Pro Facility' ? 'Đang sử dụng' : 'Chọn gói'}</Button></article>)}</div></> : <Table rowKey="id" dataSource={transactions} columns={[{ title: 'MÃ GIAO DỊCH', dataIndex: 'id' }, { title: 'NGÀY', dataIndex: 'date' }, { title: 'NỘI DUNG', dataIndex: 'description' }, { title: 'SỐ TIỀN', render: (_, item) => <span className={item.amount > 0 ? 'lime' : ''}>{formatPrice(item.amount)}</span> }, { title: 'TRẠNG THÁI', render: (_, item) => <Tag color="green">{item.status}</Tag> }, { title: '', render: () => <Button icon={<DownloadOutlined />} aria-label="Tải hóa đơn" /> }]} />}</section>
}
