import { DeleteOutlined, EditOutlined, PlusOutlined } from '@ant-design/icons'
import { Button, Form, Input, InputNumber, Modal, Switch, Table, message } from 'antd'
import { useState } from 'react'
import { formatPrice } from '../fields/field.data'
import { ownerServices, type OwnerService } from './owner.data'

export function OwnerServicesPage() {
  const [services, setServices] = useState(ownerServices); const [editing, setEditing] = useState<OwnerService | null>(); const [form] = Form.useForm<OwnerService>(); const [messageApi, contextHolder] = message.useMessage()
  const open = (service?: OwnerService) => { setEditing(service ?? null); form.setFieldsValue(service ?? { name: '', price: 0, unit: 'trận', active: true }) }
  const save = (values: OwnerService) => { if (editing) setServices((items) => items.map((item) => item.id === editing.id ? { ...item, ...values } : item)); else setServices((items) => [...items, { ...values, id: crypto.randomUUID() }]); setEditing(undefined); messageApi.success('Đã lưu dịch vụ.') }
  return <section className="owner-page">{contextHolder}<header className="user-page__head"><div><span className="eyebrow">PRICING MATRIX</span><h1>Dịch vụ & bảng giá</h1><p>Cấu hình giá sân và các tiện ích bán kèm.</p></div><Button type="primary" icon={<PlusOutlined />} onClick={() => open()}>Thêm dịch vụ</Button></header><div className="pricing-banner"><div><small>GIÁ CƠ BẢN</small><strong>{formatPrice(450000)}<em>/giờ</em></strong></div><div><small>GIỜ CAO ĐIỂM</small><strong>18:00 – 22:00</strong></div><Button icon={<EditOutlined />}>Sửa quy tắc giá</Button></div><Table rowKey="id" pagination={false} dataSource={services} columns={[{ title: 'DỊCH VỤ', dataIndex: 'name' }, { title: 'ĐƠN GIÁ', render: (_, item) => `${formatPrice(item.price)} / ${item.unit}` }, { title: 'TRẠNG THÁI', render: (_, item) => <Switch checked={item.active} onChange={(active) => setServices((items) => items.map((value) => value.id === item.id ? { ...value, active } : value))} /> }, { title: '', render: (_, item) => <div className="table-actions"><Button icon={<EditOutlined />} onClick={() => open(item)} /><Button danger icon={<DeleteOutlined />} onClick={() => setServices((items) => items.filter((value) => value.id !== item.id))} /></div> }]} /><Modal open={editing !== undefined} title={editing ? 'Chỉnh sửa dịch vụ' : 'Thêm dịch vụ'} onCancel={() => setEditing(undefined)} onOk={() => form.submit()} okText="Lưu"><Form form={form} layout="vertical" onFinish={save}><Form.Item label="TÊN DỊCH VỤ" name="name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="GIÁ" name="price" rules={[{ required: true }]}><InputNumber min={0} addonAfter="VND" /></Form.Item><Form.Item label="ĐƠN VỊ" name="unit"><Input /></Form.Item><Form.Item label="ĐANG HOẠT ĐỘNG" name="active" valuePropName="checked"><Switch /></Form.Item></Form></Modal></section>
}
