import { ArrowRightOutlined, CalendarOutlined, DollarOutlined, RiseOutlined, ShopOutlined } from '@ant-design/icons'
import { Button, Progress, Tag } from 'antd'
import { Link } from 'react-router-dom'
import { formatPrice } from '../fields/field.data'
import { ownerBookings } from './owner.data'

export function OwnerDashboardPage() {
  return <section className="owner-page"><header className="user-page__head"><div><span className="eyebrow">FACILITY COMMAND CENTER</span><h1>Chào buổi sáng, Operator.</h1><p>Tổng quan hoạt động cụm sân hôm nay.</p></div><Link to="/owner/fields/new"><Button type="primary">+ Thêm sân</Button></Link></header><div className="owner-metrics">{[{ icon: <DollarOutlined />, label: 'DOANH THU THÁNG', value: '48,6 triệu', delta: '+12.4%' }, { icon: <CalendarOutlined />, label: 'BOOKING HÔM NAY', value: '13', delta: '86% capacity' }, { icon: <ShopOutlined />, label: 'SÂN ĐANG HOẠT ĐỘNG', value: '2 / 3', delta: '1 pending' }, { icon: <RiseOutlined />, label: 'TỶ LỆ LẤP ĐẦY', value: '78%', delta: '+6.2%' }].map((item) => <article key={item.label}><span>{item.icon}</span><small>{item.label}</small><strong>{item.value}</strong><em>{item.delta}</em></article>)}</div><div className="owner-dashboard-grid"><section className="owner-panel"><header><h2>Booking gần đây</h2><Link to="/owner/bookings">Xem tất cả <ArrowRightOutlined /></Link></header>{ownerBookings.map((booking) => <Link className="owner-booking-row" to={`/owner/bookings/${booking.id}`} key={booking.id}><div><b>{booking.customer}</b><small>{booking.field} · {booking.time}</small></div><Tag color={booking.status === 'confirmed' ? 'green' : 'gold'}>{booking.status}</Tag><strong>{formatPrice(booking.amount)}</strong></Link>)}</section><section className="owner-panel utilization"><header><h2>Công suất hôm nay</h2></header><Progress type="dashboard" percent={78} strokeColor="#8cfc70" trailColor="#263125" /><p>13 / 17 khung giờ đã được đặt</p><Link to="/owner/bookings"><Button block>Xem lịch vận hành</Button></Link></section></div></section>
}
