import { CalendarOutlined, CheckOutlined, CloseOutlined, PhoneOutlined, UserOutlined } from '@ant-design/icons'
import { Button, Descriptions, Input, Modal, Result, Tag, message } from 'antd'
import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { formatPrice } from '../fields/field.data'
import { ownerBookings } from './owner.data'

export function OwnerBookingDetailPage() {
  const { bookingId = '' } = useParams(); const booking = ownerBookings.find((item) => item.id === bookingId); const [status, setStatus] = useState(booking?.status); const [notes, setNotes] = useState(booking?.notes ?? ''); const [messageApi, contextHolder] = message.useMessage()
  if (!booking) return <Result status="404" title="Không tìm thấy booking" extra={<Link to="/owner/bookings"><Button>Quay lại</Button></Link>} />
  const change = (next: 'confirmed' | 'cancelled') => Modal.confirm({ title: next === 'confirmed' ? 'Xác nhận booking này?' : 'Từ chối booking này?', content: 'Khách hàng sẽ nhận được thông báo về thay đổi trạng thái.', onOk: () => { setStatus(next); messageApi.success('Đã cập nhật trạng thái booking.') } })
  return <section className="owner-page">{contextHolder}<Link className="back-link" to="/owner/bookings">← Trở lại danh sách</Link><header className="user-page__head"><div><span className="eyebrow">BOOKING {booking.id}</span><h1>{booking.field}</h1><p><CalendarOutlined /> {booking.date} · {booking.time}</p></div><Tag color={status === 'confirmed' ? 'green' : status === 'cancelled' ? 'red' : 'gold'}>{status?.toUpperCase()}</Tag></header><div className="owner-detail-grid"><section className="owner-panel"><h2>Thông tin khách hàng</h2><Descriptions column={1} items={[{ key: 'name', label: <><UserOutlined /> Khách hàng</>, children: booking.customer }, { key: 'phone', label: <><PhoneOutlined /> Điện thoại</>, children: booking.phone }, { key: 'field', label: 'Sân', children: booking.field }]} /><h2>Ghi chú vận hành</h2><Input.TextArea rows={4} value={notes} onChange={(event) => setNotes(event.target.value)} /><Button onClick={() => messageApi.success('Đã lưu ghi chú.')}>Lưu ghi chú</Button></section><aside className="owner-panel payment-panel"><span className="eyebrow">PAYMENT STATUS</span><dl><div><dt>Tổng booking</dt><dd>{formatPrice(booking.amount)}</dd></div><div><dt>Đã đặt cọc</dt><dd className="lime">{formatPrice(booking.deposit)}</dd></div><div><dt>Còn lại</dt><dd>{formatPrice(booking.amount - booking.deposit)}</dd></div></dl>{status === 'pending' && <><Button type="primary" icon={<CheckOutlined />} block onClick={() => change('confirmed')}>Xác nhận booking</Button><Button danger icon={<CloseOutlined />} block onClick={() => change('cancelled')}>Từ chối</Button></>}</aside></div></section>
}
