import { CheckOutlined, CloseOutlined, EyeOutlined, FileTextOutlined, SearchOutlined } from '@ant-design/icons'
import { Button, Descriptions, Drawer, Input, Modal, Segmented, Table, Tag, message } from 'antd'
import { useMemo, useState } from 'react'
import { approvalRequests, type ApprovalRequest } from './admin.data'

export function AdminApprovalsPage() {
  const [type, setType] = useState<'owner' | 'field'>('owner'); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<ApprovalRequest>(); const [resolved, setResolved] = useState<string[]>([]); const [messageApi, contextHolder] = message.useMessage()
  const visible = useMemo(() => approvalRequests.filter((item) => item.type === type && !resolved.includes(item.id) && (!query || `${item.name} ${item.applicant} ${item.id}`.toLowerCase().includes(query.toLowerCase()))), [query, resolved, type])
  const decide = (request: ApprovalRequest, approve: boolean) => Modal.confirm({ title: approve ? `Phê duyệt ${request.name}?` : `Từ chối ${request.name}?`, content: approve ? 'Tài khoản hoặc sân sẽ được kích hoạt trên hệ thống.' : 'Người gửi sẽ nhận thông báo và lý do từ chối.', okText: approve ? 'Phê duyệt' : 'Từ chối', okButtonProps: { danger: !approve }, onOk: () => { setResolved((items) => [...items, request.id]); setSelected(undefined); messageApi.success(approve ? 'Đã phê duyệt hồ sơ.' : 'Đã từ chối hồ sơ.') } })
  return <section className="admin-page">{contextHolder}<header className="user-page__head"><div><span className="eyebrow">VERIFICATION QUEUE</span><h1>Phê duyệt chủ sân & sân</h1><p>Kiểm tra hồ sơ, tài liệu và mức độ rủi ro trước khi kích hoạt.</p></div></header><div className="admin-toolbar"><Segmented value={type} onChange={setType} options={[{ value: 'owner', label: 'Chủ sân chờ duyệt' }, { value: 'field', label: 'Sân chờ duyệt' }]} /><Input prefix={<SearchOutlined />} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm hồ sơ..." /></div><Table rowKey="id" dataSource={visible} scroll={{ x: 900 }} columns={[{ title: 'HỒ SƠ', render: (_, item) => <><b>{item.name}</b><small className="table-sub">{item.id}</small></> }, { title: 'ĐƠN VỊ', dataIndex: 'applicant' }, { title: 'KHU VỰC', dataIndex: 'location' }, { title: 'TÀI LIỆU', render: (_, item) => <><FileTextOutlined /> {item.documents} tệp</> }, { title: 'RỦI RO', render: (_, item) => <Tag color={item.risk === 'low' ? 'green' : 'gold'}>{item.risk.toUpperCase()}</Tag> }, { title: 'GỬI LÚC', dataIndex: 'submittedAt' }, { title: '', render: (_, item) => <Button icon={<EyeOutlined />} onClick={() => setSelected(item)}>Kiểm tra</Button> }]} /><Drawer width={520} open={Boolean(selected)} onClose={() => setSelected(undefined)} title="Chi tiết hồ sơ">{selected && <div className="approval-detail"><Tag color="green">{selected.type.toUpperCase()} APPLICATION</Tag><h2>{selected.name}</h2><Descriptions column={1} items={[{ key: 'id', label: 'Mã hồ sơ', children: selected.id }, { key: 'applicant', label: 'Đơn vị', children: selected.applicant }, { key: 'location', label: 'Địa chỉ', children: selected.location }, { key: 'submitted', label: 'Thời gian gửi', children: selected.submittedAt }, { key: 'documents', label: 'Tài liệu đính kèm', children: `${selected.documents} tệp đã quét an toàn` }]} /><div className="document-placeholder"><FileTextOutlined /><span>BUSINESS_LICENSE.PDF</span><Button>Xem tài liệu</Button></div><footer><Button danger icon={<CloseOutlined />} onClick={() => decide(selected,false)}>Từ chối</Button><Button type="primary" icon={<CheckOutlined />} onClick={() => decide(selected,true)}>Phê duyệt</Button></footer></div>}</Drawer></section>
}
