import { AlertOutlined, ApiOutlined, ArrowRightOutlined, CheckCircleFilled, ClockCircleOutlined, DatabaseOutlined, DollarOutlined, ShopOutlined, TeamOutlined } from '@ant-design/icons'
import { Progress, Tag } from 'antd'
import { Link } from 'react-router-dom'
import { approvalRequests, auditLogs, managedUsers, moderationItems } from './admin.data'

export function AdminDashboardPage() {
  const metrics = [{ label: 'NGƯỜI DÙNG', value: managedUsers.length.toLocaleString('vi-VN'), delta: '+8.2%', icon: <TeamOutlined /> }, { label: 'SÂN HOẠT ĐỘNG', value: '148', delta: '+12 tháng này', icon: <ShopOutlined /> }, { label: 'GMV THÁNG', value: '2,48 tỷ', delta: '+16.4%', icon: <DollarOutlined /> }, { label: 'CẦN XỬ LÝ', value: String(approvalRequests.length + moderationItems.filter((item) => item.status === 'pending').length), delta: 'queue items', icon: <AlertOutlined /> }]
  return <section className="admin-page"><header className="user-page__head"><div><span className="eyebrow">SYSTEM COMMAND CENTER</span><h1>Admin Dashboard</h1><p>Toàn cảnh vận hành mạng lưới PitchMaster.</p></div><Tag color="green"><CheckCircleFilled /> ALL SYSTEMS OPERATIONAL</Tag></header><div className="admin-metrics">{metrics.map((item) => <article key={item.label}><span>{item.icon}</span><small>{item.label}</small><strong>{item.value}</strong><em>{item.delta}</em></article>)}</div><div className="admin-command-grid"><section className="admin-panel"><header><h2>Hoạt động hệ thống</h2><span className="eyebrow">LIVE / 30 DAYS</span></header><div className="activity-chart" aria-label="Biểu đồ hoạt động 30 ngày">{[38,45,42,61,58,67,75,69,83,77,92,86].map((height,index) => <i key={index} style={{ height: `${height}%` }} />)}</div></section><section className="admin-panel health-panel"><header><h2>System health</h2></header>{[{ icon: <ApiOutlined />, name: 'API Gateway', value: 99 }, { icon: <DatabaseOutlined />, name: 'Database Cluster', value: 96 }, { icon: <ClockCircleOutlined />, name: 'Realtime Service', value: 98 }].map((node) => <div key={node.name}><span>{node.icon} {node.name}</span><Progress percent={node.value} size="small" strokeColor="#8cfc70" trailColor="#263125" /></div>)}</section><section className="admin-panel queue-panel"><header><h2>Hàng đợi ưu tiên</h2><Link to="/admin/approvals">Mở queue <ArrowRightOutlined /></Link></header>{approvalRequests.slice(0,3).map((request) => <div key={request.id}><span><b>{request.name}</b><small>{request.type.toUpperCase()} · {request.submittedAt}</small></span><Tag color={request.risk === 'low' ? 'green' : 'gold'}>{request.risk} risk</Tag></div>)}</section><section className="admin-panel"><header><h2>Audit gần đây</h2><Link to="/admin/reports">Xem tất cả <ArrowRightOutlined /></Link></header>{auditLogs.map((log) => <div className="audit-line" key={log.id}><i /><span><b>{log.action}</b><small>{log.actor} → {log.target}</small></span><time>{log.time.split(' ')[1]}</time></div>)}</section></div></section>
}
