import { DeleteOutlined, EyeOutlined, SearchOutlined, StopOutlined, UndoOutlined } from '@ant-design/icons'
import { Button, Input, Modal, Segmented, Table, Tag, message } from 'antd'
import { useMemo, useState } from 'react'
import { managedUsers, moderationItems } from './admin.data'

type ManagementTab = 'users' | 'posts' | 'reviews'
export function AdminManagementPage() {
  const [tab, setTab] = useState<ManagementTab>('users'); const [query, setQuery] = useState(''); const [userStates, setUserStates] = useState<Record<string,string>>({}); const [removed, setRemoved] = useState<string[]>([]); const [messageApi, contextHolder] = message.useMessage()
  const users = useMemo(() => managedUsers.filter((user) => !query || `${user.name} ${user.email} ${user.id}`.toLowerCase().includes(query.toLowerCase())), [query])
  const content = moderationItems.filter((item) => item.type === (tab === 'posts' ? 'post' : 'review') && !removed.includes(item.id))
  const toggleUser = (id: string, current: string) => Modal.confirm({ title: current === 'suspended' ? 'Khôi phục tài khoản?' : 'Tạm khóa tài khoản?', content: 'Thao tác sẽ được ghi vào audit log.', onOk: () => { setUserStates((states) => ({ ...states, [id]: current === 'suspended' ? 'active' : 'suspended' })); messageApi.success('Đã cập nhật trạng thái tài khoản.') } })
  return <section className="admin-page">{contextHolder}<header className="user-page__head"><div><span className="eyebrow">PLATFORM GOVERNANCE</span><h1>Quản lý & kiểm duyệt</h1><p>Điều hành người dùng, bài đăng và đánh giá trên toàn hệ thống.</p></div></header><div className="admin-toolbar"><Segmented value={tab} onChange={setTab} options={[{ value: 'users', label: 'Người dùng' }, { value: 'posts', label: 'Bài đăng' }, { value: 'reviews', label: 'Đánh giá' }]} /><Input prefix={<SearchOutlined />} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm kiếm..." /></div>{tab === 'users' ? <Table rowKey="id" dataSource={users} scroll={{ x: 900 }} columns={[{ title: 'NGƯỜI DÙNG', render: (_, item) => <><b>{item.name}</b><small className="table-sub">{item.email} · {item.id}</small></> }, { title: 'VAI TRÒ', render: (_, item) => <Tag>{item.role}</Tag> }, { title: 'THAM GIA', dataIndex: 'joinedAt' }, { title: 'BÁO CÁO', render: (_, item) => <span className={item.reports ? 'warning-text' : ''}>{item.reports}</span> }, { title: 'TRẠNG THÁI', render: (_, item) => { const status = userStates[item.id] ?? item.status; return <Tag color={status === 'active' ? 'green' : 'red'}>{status}</Tag> } }, { title: '', render: (_, item) => { const status = userStates[item.id] ?? item.status; return <div className="table-actions"><Button icon={<EyeOutlined />} /><Button danger={status !== 'suspended'} icon={status === 'suspended' ? <UndoOutlined /> : <StopOutlined />} onClick={() => toggleUser(item.id,status)} /></div> } }]} /> : <div className="moderation-list">{content.map((item) => <article key={item.id}><header><Tag color={item.type === 'post' ? 'blue' : 'purple'}>{item.type.toUpperCase()}</Tag><Tag color={item.status === 'pending' ? 'gold' : 'green'}>{item.status}</Tag><time>{item.reportedAt}</time></header><h2>{item.reason}</h2><p>{item.content}</p><footer><span>Đăng bởi <b>{item.author}</b></span><div><Button icon={<EyeOutlined />}>Xem ngữ cảnh</Button><Button danger icon={<DeleteOutlined />} onClick={() => Modal.confirm({ title: 'Gỡ nội dung này?', content: 'Nội dung sẽ bị ẩn và tác giả nhận thông báo.', onOk: () => { setRemoved((items) => [...items,item.id]); messageApi.success('Đã gỡ nội dung.') } })}>Gỡ nội dung</Button></div></footer></article>)}</div>}</section>
}
