import { AlertOutlined, CheckCircleFilled, CloudServerOutlined, DownloadOutlined, FileSearchOutlined } from '@ant-design/icons'
import { Button, DatePicker, Progress, Segmented, Table, Tag } from 'antd'
import { useState } from 'react'
import { auditLogs, moderationItems } from './admin.data'

export function AdminReportsPage() {
  const [tab, setTab] = useState<'reports' | 'audit' | 'system'>('reports')
  return <section className="admin-page"><header className="user-page__head"><div><span className="eyebrow">OBSERVABILITY & COMPLIANCE</span><h1>Báo cáo hệ thống</h1><p>Phân tích kiểm duyệt, audit trail và tình trạng hạ tầng.</p></div><Button icon={<DownloadOutlined />}>Xuất báo cáo</Button></header><div className="admin-toolbar"><Segmented value={tab} onChange={setTab} options={[{ value: 'reports', label: 'Báo cáo kiểm duyệt' }, { value: 'audit', label: 'Audit log' }, { value: 'system', label: 'System status' }]} /><DatePicker.RangePicker /></div>{tab === 'reports' && <><div className="report-metrics"><article><AlertOutlined /><strong>{moderationItems.length}</strong><span>Tổng báo cáo</span></article><article><FileSearchOutlined /><strong>{moderationItems.filter((item) => item.status === 'pending').length}</strong><span>Đang chờ xử lý</span></article><article><CheckCircleFilled /><strong>94%</strong><span>Xử lý dưới 24 giờ</span></article></div><Table rowKey="id" dataSource={moderationItems} columns={[{ title: 'MÃ', dataIndex: 'id' }, { title: 'LOẠI', dataIndex: 'type' }, { title: 'LÝ DO', dataIndex: 'reason' }, { title: 'TÁC GIẢ', dataIndex: 'author' }, { title: 'THỜI GIAN', dataIndex: 'reportedAt' }, { title: 'TRẠNG THÁI', render: (_, item) => <Tag color={item.status === 'pending' ? 'gold' : 'green'}>{item.status}</Tag> }]} /></>}{tab === 'audit' && <Table rowKey="id" dataSource={auditLogs} scroll={{ x: 800 }} columns={[{ title: 'EVENT ID', dataIndex: 'id' }, { title: 'ACTOR', dataIndex: 'actor' }, { title: 'ACTION', render: (_, item) => <code>{item.action}</code> }, { title: 'TARGET', dataIndex: 'target' }, { title: 'TIME', dataIndex: 'time' }, { title: 'IP', dataIndex: 'ip' }]} />}{tab === 'system' && <div className="system-grid">{[{ name: 'API Gateway', percent: 99, detail: '42 ms avg latency' }, { name: 'Primary Database', percent: 96, detail: '18% storage used' }, { name: 'Socket Cluster', percent: 98, detail: '1,842 active connections' }, { name: 'Object Storage', percent: 100, detail: 'Operational' }].map((node) => <article key={node.name}><CloudServerOutlined /><div><h2>{node.name}</h2><p>{node.detail}</p><Progress percent={node.percent} strokeColor="#8cfc70" trailColor="#263125" /></div><Tag color="green">OPERATIONAL</Tag></article>)}</div>}</section>
}
